name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "Building Docker image $IMAGE_NAME:$IMAGE_TAG"
          # docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          echo "Pushing Docker image $IMAGE_NAME:$IMAGE_TAG"
          # docker push <registry-url>/$IMAGE_NAME:$IMAGE_TAG

  deploy-dev:
    name: Deploy to Dev
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy to Dev
        run: |
          echo "Deploying image $IMAGE_NAME:$IMAGE_TAG to DEV environment"
          # your deployment commands for dev go here

  deploy-stage:
    name: Deploy to Stage
    needs: build
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Deploy to Stage
        run: |
          echo "Deploying image $IMAGE_NAME:$IMAGE_TAG to STAGE environment"
          # your deployment commands for stage go here
